### ISSUE TITLE
Plan for a release yet?

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/date_ical#2]
@jlfranklin first of all, thank you for porting date_ical to Backdrop.

There hasn't been a release yet. Are there any plans for a release, or is the fact, that the required external library made incompatible changes a show stopper?

Or possibly you just didn't find the time yet.

Whatever it is, please let the community know. Maybe I can help out a bit.

**Comment by jlfranklin** [comment]
It's been a while since I looked at this module.  Thanks for the interest and bringing it back on my radar.

It looks like there is one issue outstanding, backdrop-contrib/date_ical#1.   That depends on backdrop/backdrop-issues#1739 getting added to core.  Can you take a swing at the core bug?  That should pave the way for this to be released.

**Comment by indigoxela** [comment]
> Can you take a swing at the core bug?

That issue is probably beyond my scope.

**Comment by indigoxela** [comment]
What about another approach: module entity_plus comes with function entity_plus_view(), which returns a renderable array.

That would, of course, bring another dependency.

**Comment by jlfranklin** [comment]
Additional dependencies are fine.  As long as it works.

**Comment by indigoxela** [comment]
I posted a pull request for #1 

For now I solved my problem with a [custom module](https://github.com/indigoxela/viewsicalexport), so this issue here doesn't have high priority for me anymore.
